# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
   
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2-beta

      
      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node version: 12   
      - uses: borales/actions-yarn@v1.22.5
         with
         cmd:install 
         
       
          
      - name: build react app
        run: yarn build
      - name: install surge
        run: npm install --global surge
      - name: deploy to surge
        run: surge ./build react-expense-app-by.surge.sh -token${{secrets.SURGE_TOKEN}}
